debug: 'false'
logging:
  level:
    de:
      flashheart: DEBUG

spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceId: myscheduler


server:
  error:
    include-stacktrace: always
  servlet:
    session:
      timeout: 60

mqtt:
  cleanSession: 'true'
  connectionTimeout: '10'
  automaticReconnect: 'true'

rlgs:
  score_broadcast:
    every_seconds: '0.5'
    cycle_counter: '10'
  intro:
    bf3: Battlefield 3
  access_points:
    00223f97a198: NETGEAR
  users:
    - username: default_user # pw 12345
      password: $2b$12$5/8pFYfQVRLO5djo/bBh0.BUyW6PjAQMitC1.BDTtyUrZN0N3N4H2
      api_key: D84C6904-8EB0-4C78-8598-6149597EB170



