debug: 'false'

logging:
  level:
    de:
      flashheart:
        rlg: INFO
    org:
      eclipse:
        paho:
          client:
            mqttv3: INFO
    root: INFO

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceId: my_scheduler
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/rlgs_db
  jpa:
    show-sql: true
  liquibase:
    enabled: false

rlgs:
  intros:
    bf3: Battlefield 3
  voices:
    sharon30s: Sharon (AI)
  access_points:
    00223f97a198: NETGEAR
  score_broadcast:
    every_seconds: '0.5'
    cycle_counter: '10'

mqtt:
  qos: 2
  outbound:
    topic: rlg/cmd/
    # client can subscribe to this topic to be informed about occurring events
    # every game id has its own subtopics like rlg/notify/1
    # agent events (independent of a running game) are posted below the game topics in rlg/notify
    notification_topic: rlg/notify/
  inbound:
    topic: rlg/evt/#
  client_id: rlgcmd@release
  host: localhost
  port: 1883
  ws_port: 8080
  max_inflight: 1000
  automaticReconnect: 'true'

server:
  port: 8090
  locale:
    default: de
  servlet:
    session:
      timeout: 1440m
  error:
    include-stacktrace: always
