### note to myself (ntm)
# this is the basic application configuration which resides inside the application package.
# it is read before any other configuration
# the externalized application.yml (the one in the config file OUTSIDE the project)
# only adds to or overrides the settings in this file - the one below

debug: 'false'

logging:
  level:
    de:
      flashheart:
        rlg: INFO
    org:
      eclipse:
        paho:
          client:
            mqttv3: INFO
    root: INFO

# this is the standard setup for the docker container
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceId: my_scheduler
  application:
    name: rlgcommander
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/rlgs_db
    username: rlgs_user
    password: 83jg00hm1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml

rlgs:
  intros:
    bf3: Battlefield 3
  voices:
    sharon30s: Sharon (AI)
  access_points:
    00223f97a198: NETGEAR

mqtt:
  qos: 2
  outbound:
    topic: rlg/cmd/
    # client can subscribe to this topic to be informed about occurring events
    # every game id has its own subtopics like rlg/notify/1
    # agent events (independent of a running game) are posted below the game topics in rlg/notify
    notification_topic: rlg/notify/
    # todo: extend for agents and score and time broadcasts
  inbound:
    topic: rlg/evt/#
  client_id: rlgcmd@release
  host: broker
  port: 1883
  ws_port: 8080
  max_inflight: 1000
  automaticReconnect: 'true'

server:
  port: 8090
  locale:
    default: de
  servlet:
    session:
      timeout: 1440m
  error:
    include-stacktrace: always
